### ISSUE TITLE
ManageIQ Operator

### ISSUE THREAD

**Issue by gyliu513** [gyliu513/roadmap#11]
```
oc adm policy add-scc-to-user anyuid system:serviceaccount:default:inframanagement-anyuid
oc adm policy add-scc-to-user anyuid system:serviceaccount:default:inframanagement-orchestrator
oc adm policy add-scc-to-user anyuid system:serviceaccount:default:inframanagement-httpd
```

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo-2
spec:
  securityContext:
    privileged: true
```
