### ISSUE TITLE
interface of HA

### ISSUE THREAD

**Issue by gyliu513** [gyliu513/roadmap#13]
```yaml
kind: NodeHAController
apiVersion: node.hacontroller.io/v1alpha1
metadata:
  name: my-node-ha-contrtoller
spec:
  key: value
---
kind: HAController
apiVersion: hacontroller.io/v1alpha1
metadata:
  name: my-ha-controller
spec:
  haControllerRef:
    kind: NodeHAController
    apiVersion: node.hacontroller.io/v1alpha1
    name: my-node-ha-contrtoller
```

```yaml
kind: ClusterHAController
apiVersion: cluster.hacontroller.io/v1alpha1
metadata:
  name: my-cluster-ha-contrtoller
spec:
  key: value
---
kind: HAController
apiVersion: hacontroller.io/v1alpha1
metadata:
  name: my-ha-controller
spec:
  haControllerRef:
    kind: ClusterHAController
    apiVersion: cluster.hacontroller.io/v1alpha1
    name: my-cluster-ha-contrtoller
```

```yaml
kind: AppHAController
apiVersion: app.hacontroller.io/v1alpha1
metadata:
  name: my-app-ha-contrtoller
spec:
  key: value
---
kind: HAController
apiVersion: hacontroller.io/v1alpha1
metadata:
  name: my-ha-controller
spec:
  haControllerRef:
    kind: AppHAController
    apiVersion: app.hacontroller.io/v1alpha1
    name: my-app-ha-contrtoller
```

```yaml
kind: FooHAController
apiVersion: foo.hacontroller.io/v1alpha1
metadata:
  name: my-foo-ha-contrtoller
spec:
  key: value
---
kind: HAController
apiVersion: hacontroller.io/v1alpha1
metadata:
  name: my-foo-controller
spec:
  haControllerRef:
    kind: FooHAController
    apiVersion: foo.hacontroller.io/v1alpha1
    name: my-foo-ha-contrtoller
```
