### ISSUE TITLE
CatalogSource and imagePullSecrets

### ISSUE THREAD

**Issue by gyliu513** [gyliu513/roadmap#17]
```yaml
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: my-catalog
  namespace: default
spec:
  name: my-catalog
  sourceType: grpc
  image: <your catalog image>
  secrets:
  - my-pull-secret
```
